### ISSUE TITLE
sicktoolbox_wrapper for ARM

### ISSUE THREAD

**Issue by Tal-seven** [ros-drivers/sicktoolbox_wrapper#4]
Hello,

I have been trying for a week to get my sick lms 200 working on UDOO quad. I am unable to access it as a /dev/ttyUSB\* or /dev/ttyACM\* device. I have installed the sicktoolbox_wrapper for arm based devices. Could any one please point me in the right direction. I have also  compiled the kernel with cdc_acm enabled, but with no luck.  Please do help me if you can.

**Comment by trainman419** [comment]
Redirected from ROS Answers: http://answers.ros.org/question/190925/udoo-sicktoolbox/?comment=191137

A quick google search suggests that the LMS200 is not a USB device. Are you using a USB to serial converter?

It sounds like you really have two problems here:
1. The driver for your USB to serial convertor doesn't work
2. The sicktoolbox_wrapper driver hangs when run on ARM

You'll have do most of the work to resolve (1) on your own. I can give you some guidance, but because we don't have an UDOO or your USB to serial interface, I can't do much more than that.

I'll spend a few minutes trying out the Sick utilities on one of my ARM boards and on a regular x86 machine to see if I spot any obvious bad behaviors.

**Comment by trainman419** [comment]
I tried out the sicklms node on one of my ARM boards, and it looks like it behaves as expected: I don't have a Sick plugged in, so it prints an error and exits:

```
$ rosrun sicktoolbox_wrapper sicklms 

        *** Attempting to initialize the Sick LMS...
        Attempting to open device @ /dev/lms200
ERROR: I/O exception - SickLMS2xx::_setupConnection: - Unable to open serial port
ERROR: I/O exception - SickLMS2xx::_setupConnection: - Unable to open serial port
[ERROR] [1408948195.333907084]: Initialize failed! are you using the correct device path?
```

This is running Indigo instead of Hydro, but it doesn't look like the driver has changed between versions, so it's probably still a valid test. At the very least, it proves that the sicklms node is a properly compiled binary, and doesn't hang during startup on my system.

What output do you get if you run the sicklms node, without your sensor plugged in?

**Comment by Tal-seven** [comment]
It tries to connect to the serial port and after a very long time i get an error similar to yours. M even unable to see my device as a /dev/ttyUSB\* device. You are right, i guess its the USB-Serial driver which is causing the problem. But could you guide me to a place where i could get some help with this. I have tried connecting a USB flash drive. It is getting detected but my board doesnt create a device node for it.

**Comment by trainman419** [comment]
The kernel and modules on the UDOO site, version 2.1, release 2014-07-31, contains both the ftdi_sio and cdc-acm modules: http://www.udoo.org/downloads/

If installing those doesn't work, or you don't know how to install them, or have other troubles with the UDOO, I would recommend asking on their forum: http://www.udoo.org/forum/

**Comment by trainman419** [comment]
Were you able to install the kernel modules for your USB to serial converter? Do you have any notes from that process for future users who run into the same problem?

**Comment by Tal-seven** [comment]
I have partially solved the problem. I can now see the device as a /dev/ttyUSB0 and access it. It was a permission problem initially, i had to create a rule under /etc/udev/rules.d/ and ensure that the ftdi_sio was being loaded at startup. However the sicktoolbox doesnt detect the baud rate whenever i run it. I've set the permissions right, changed the baud rate to 38400 and 19200. It either says "unable to detect baud rate" or waits forever at initiation screen. dmesg gives an error which says "ftdi_sio unable to read latency timer". Trying to find a solution for this.
